In [2]:
#Kalayaporn Wangsthaporn
#Python 3
#Assignment 2
#09/17/2018

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

/Users/kalayaporn/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [3]:
# reading the data (.csv) by using pandas command

data = pd.read_csv("/Users/kalayaporn/Desktop/Fall 2018/FERM 6V99/assignment 3/compustat_annual_2000_2017_with link information.csv")

/Users/kalayaporn/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (2,17,33,37,955,956,957,962,976,977,982) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
# Looking few top rows by using the function head()

data.head()

,GVKEY,LINKPRIM,LIID,LINKTYPE,LPERMNO,LPERMCO,LINKDT,LINKENDDT,datadate,fyear,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
0,1004,P,1,LU,54594,20000,19720424,E,20000531,1999.0,...,1,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,NaN,19880101.0
1,1004,P,1,LU,54594,20000,19720424,E,20010531,2000.0,...,1,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,NaN,19880101.0
2,1004,P,1,LU,54594,20000,19720424,E,20020531,2001.0,...,1,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,NaN,19880101.0
3,1004,P,1,LU,54594,20000,19720424,E,20030531,2002.0,...,1,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,NaN,19880101.0
4,1004,P,1,LU,54594,20000,19720424,E,20040531,2003.0,...,1,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,NaN,19880101.0

In [5]:
# Checking missing value for each variables (columns)

data.isnull().sum()

GVKEY             0
LINKPRIM          0
LIID              0
LINKTYPE          0
LPERMNO           0
LPERMCO           0
LINKDT            0
LINKENDDT         0
datadate          0
fyear             2
indfmt            0
consol            0
popsrc            0
datafmt           0
tic               0
cusip             0
conm              0
acctchg      103138
acctstd       10256
acqmeth       92971
adrr         101985
ajex              4
ajp              10
bspr          88056
compst        83289
curcd             2
curncd            2
currtr            2
curuscn      104682
final         11065
              ...
addzip         1211
busdesc          12
city              0
conml             0
county       108606
dlrsn         69798
ein           20742
fax           50684
fyrc              0
ggroup        10268
gind          10268
gsector       10268
gsubind       10268
idbflag           0
incorp        15253
loc               0
naics           496
phone          1952
prican       104089
prirow       101754
priusa            0
sic               0
spcindcd      23853
spcseccd      23853
spcsrc        38266
state         12769
stko          10180
weburl        21037
dldte         69798
ipodate       49598
Length: 988, dtype: int64

In [6]:
# Statistics for numberical variables
# Summary of numerical fields by using describe() function

data.describe()

,GVKEY,LPERMNO,LPERMCO,LINKDT,datadate,fyear,adrr,ajex,ajp,currtr,...,gsector,gsubind,naics,priusa,sic,spcindcd,spcseccd,stko,dldte,ipodate
count,108683.000000,108683.000000,108683.000000,1.086830e+05,1.086830e+05,108681.000000,6698.000000,108679.000000,108673.000000,108681.000000,...,98415.000000,9.841500e+04,108187.000000,108683.000000,108683.000000,84830.000000,84830.000000,98503.000000,3.888500e+04,5.908500e+04
mean,69476.671476,69759.034762,26647.940276,1.994389e+07,2.007922e+07,2007.702717,22.534141,1.359831,1.358979,0.982204,...,33.051567,3.322905e+07,425525.058075,6.517201,5035.589991,447.318213,895.012012,0.427936,2.010941e+07,1.998359e+07
std,66839.321302,26796.975699,16648.325474,1.227137e+05,5.186442e+04,5.204203,192.219260,20.354188,20.354689,0.153100,...,12.639010,1.263001e+07,151265.866481,21.257467,1967.654382,260.203508,87.325550,1.045503,4.406561e+04,7.620185e+04
min,1004.000000,10001.000000,5.000000,1.962010e+07,2.000013e+07,1999.000000,0.000200,0.000000,0.000000,0.000100,...,10.000000,1.010101e+07,42.000000,1.000000,100.000000,110.000000,600.000000,0.000000,2.000062e+07,1.949050e+07
25%,14225.000000,61496.000000,12954.000000,1.989010e+07,2.003123e+07,2003.000000,1.000000,1.000000,1.000000,1.000000,...,25.000000,2.510101e+07,332510.000000,1.000000,3572.000000,220.000000,800.000000,0.000000,2.007100e+07,1.994080e+07
50%,30094.000000,81481.000000,21396.000000,1.996110e+07,2.007123e+07,2007.000000,2.000000,1.000000,1.000000,1.000000,...,35.000000,3.520101e+07,484230.000000,1.000000,5140.000000,360.000000,925.000000,0.000000,2.012011e+07,1.998022e+07
75%,133104.000000,88457.000000,42999.000000,2.003040e+07,2.012123e+07,2012.000000,6.000000,1.000000,1.000000,1.000000,...,45.000000,4.510101e+07,524126.000000,1.000000,6726.000000,815.000000,970.000000,0.000000,2.015022e+07,2.003122e+07
max,319507.000000,93436.000000,56209.000000,2.017122e+07,2.017123e+07,2017.000000,5000.000000,1500.000000,1500.000000,2.038900,...,60.000000,6.010204e+07,999990.000000,99.000000,9998.000000,850.000000,978.000000,3.000000,2.018031e+07,2.017122e+07

In [7]:
# Removing non-numerical variables

dataset = data.select_dtypes(include = [np.number])

In [8]:
# Removing variables (Column) with more than 70% missing

wdrs = dataset[dataset.columns[dataset.isnull().sum()/dataset.shape[0]<0.7]]
wdrs

,GVKEY,LPERMNO,LPERMCO,LINKDT,datadate,fyear,ajex,ajp,currtr,fyr,...,gsector,gsubind,naics,priusa,sic,spcindcd,spcseccd,stko,dldte,ipodate
0,1004,54594,20000,19720424,20000531,1999.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
1,1004,54594,20000,19720424,20010531,2000.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
2,1004,54594,20000,19720424,20020531,2001.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
3,1004,54594,20000,19720424,20030531,2002.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
4,1004,54594,20000,19720424,20040531,2003.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
5,1004,54594,20000,19720424,20050531,2004.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
6,1004,54594,20000,19720424,20060531,2005.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
7,1004,54594,20000,19720424,20070531,2006.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
8,1004,54594,20000,19720424,20080531,2007.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
9,1004,54594,20000,19720424,20090531,2008.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
10,1004,54594,20000,19720424,20100531,2009.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
11,1004,54594,20000,19720424,20110531,2010.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
12,1004,54594,20000,19720424,20120531,2011.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
13,1004,54594,20000,19720424,20130531,2012.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
14,1004,54594,20000,19720424,20140531,2013.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
15,1004,54594,20000,19720424,20150531,2014.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
16,1004,54594,20000,19720424,20160531,2015.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
17,1004,54594,20000,19720424,20170531,2016.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,NaN,19880101.0
18,1013,50906,2902,19790316,20001031,2000.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
19,1013,50906,2902,19790316,20011031,2001.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
20,1013,50906,2902,19790316,20021031,2002.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
21,1013,50906,2902,19790316,20031031,2003.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
22,1013,50906,2902,19790316,20041031,2004.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
23,1013,50906,2902,19790316,20051031,2005.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
24,1013,50906,2902,19790316,20061031,2006.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
25,1013,50906,2902,19790316,20071031,2007.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
26,1013,50906,2902,19790316,20081031,2008.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
27,1013,50906,2902,19790316,20090930,2009.0,1.0000,1.0000,1.0000,9.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
28,1013,50906,2902,19790316,20100930,2010.0,1.0000,1.0000,1.0000,9.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
29,1034,65832,20007,19840215,20001231,2000.0,1.0000,1.0000,1.0000,12.0,...,35.0,35202010.0,325412.0,1,2834,283.0,905.0,0.0,20081231.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108653,315318,14406,54703,20140123,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,15.0,15101050.0,325320.0,1,2870,NaN,NaN,0.0,NaN,NaN
108654,315318,14406,54703,20140123,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,15.0,15101050.0,325320.0,1,2870,NaN,NaN,0.0,NaN,NaN
108655,315629,16348,55719,20161101,20161231,2016.0,1.0000,1.0000,0.0309,12.0,...,45.0,45301020.0,334418.0,90,3679,NaN,NaN,0.0,NaN,NaN
108656,315629,16348,55719,20161101,20171231,2017.0,1.0000,1.0000,0.0337,12.0,...,45.0,45301020.0,334418.0,90,3679,NaN,NaN,0.0,NaN,NaN
108657,315639,15419,55305,20150619,20151231,2015.0,1.0000,1.0000,1.0859,12.0,...,35.0,35201010.0,325414.0,90,2836,NaN,NaN,0.0,NaN,NaN
108658,315639,15419,55305,20150619,20161231,2016.0,1.0000,1.0000,1.0552,12.0,...,35.0,35201010.0,325414.0,90,2836,NaN,NaN,0.0,NaN,NaN
108659,315639,15419,55305,20150619,20171231,2017.0,1.0000,1.0000,1.2022,12.0,...,35.0,35201010.0,325414.0,90,2836,NaN,NaN,0.0,NaN,NaN
108660,315887,14344,54677,20131212,20131231,2013.0,0.0833,0.0833,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20131212.0
108661,315887,14344,54677,20131212,20141231,2014.0,0.0833,0.0833,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20131212.0
108662,315887,14344,54677,20131212,20151231,2015.0,1.0000,1.0000,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20131212.0
108663,315887,14344,54677,20131212,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20131212.0
108664,315887,14344,54677,20131212,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20131212.0
108665,316056,14297,54641,20131202,20131231,2013.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,NaN,NaN,0.0,NaN,NaN
108666,316056,14297,54641,20131202,20141231,2014.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,NaN,NaN,0.0,NaN,NaN
108667,316056,14297,54641,20131202,20151231,2015.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,NaN,NaN,0.0,NaN,NaN
108668,316056,14297,54641,20131202,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,NaN,NaN,0.0,NaN,NaN
108669,316056,14297,54641,20131202,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,NaN,NaN,0.0,NaN,NaN
108670,317260,14756,54928,20140612,20141231,2014.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,NaN,NaN,0.0,NaN,NaN
108671,317260,14756,54928,20140612,20151231,2015.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,NaN,NaN,0.0,NaN,NaN
108672,317260,14756,54928,20140612,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,NaN,NaN,0.0,NaN,NaN
108673,317260,14756,54928,20140612,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,NaN,NaN,0.0,NaN,NaN
108674,317264,14642,54852,20140508,20150331,2014.0,1.0000,1.0000,1.0000,3.0,...,10.0,10102040.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20140508.0
108675,317264,14642,54852,20140508,20160331,2015.0,1.0000,1.0000,1.0000,3.0,...,10.0,10102040.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20140508.0
108676,317264,14642,54852,20140508,20170331,2016.0,1.0000,1.0000,1.0000,3.0,...,10.0,10102040.0,483111.0,1,4412,NaN,NaN,0.0,NaN,20140508.0
108677,317427,15920,55515,20160112,20161231,2016.0,1.0000,1.0000,1.0552,12.0,...,30.0,30202030.0,311411.0,1,2030,NaN,NaN,0.0,NaN,NaN
108678,318728,16496,55804,20161209,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,40.0,40301020.0,524113.0,1,6311,NaN,NaN,0.0,NaN,20161209.0
108679,318728,16496,55804,20161209,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,40.0,40301020.0,524113.0,1,6311,NaN,NaN,0.0,NaN,20161209.0
108680,318815,15904,55506,20151207,20151231,2015.0,1.0000,1.0000,1.4746,12.0,...,35.0,35201010.0,325414.0,90,2836,NaN,NaN,0.0,NaN,NaN
108681,318815,15904,55506,20151207,20161231,2016.0,1.0000,1.0000,1.2337,12.0,...,35.0,35201010.0,325414.0,90,2836,NaN,NaN,0.0,NaN,NaN
108682,319507,16469,55793,20161118,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,35.0,35202010.0,325414.0,90,2836,NaN,NaN,0.0,NaN,NaN

In [9]:
# Filling the missing value with median of each column

wdrsdata = wdrs.fillna(wdrs.median())
wdrsdata

,GVKEY,LPERMNO,LPERMCO,LINKDT,datadate,fyear,ajex,ajp,currtr,fyr,...,gsector,gsubind,naics,priusa,sic,spcindcd,spcseccd,stko,dldte,ipodate
0,1004,54594,20000,19720424,20000531,1999.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
1,1004,54594,20000,19720424,20010531,2000.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
2,1004,54594,20000,19720424,20020531,2001.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
3,1004,54594,20000,19720424,20030531,2002.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
4,1004,54594,20000,19720424,20040531,2003.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
5,1004,54594,20000,19720424,20050531,2004.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
6,1004,54594,20000,19720424,20060531,2005.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
7,1004,54594,20000,19720424,20070531,2006.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
8,1004,54594,20000,19720424,20080531,2007.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
9,1004,54594,20000,19720424,20090531,2008.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
10,1004,54594,20000,19720424,20100531,2009.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
11,1004,54594,20000,19720424,20110531,2010.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
12,1004,54594,20000,19720424,20120531,2011.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
13,1004,54594,20000,19720424,20130531,2012.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
14,1004,54594,20000,19720424,20140531,2013.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
15,1004,54594,20000,19720424,20150531,2014.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
16,1004,54594,20000,19720424,20160531,2015.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
17,1004,54594,20000,19720424,20170531,2016.0,1.0000,1.0000,1.0000,5.0,...,20.0,20101010.0,423860.0,1,5080,110.0,925.0,0.0,20120109.0,19880101.0
18,1013,50906,2902,19790316,20001031,2000.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
19,1013,50906,2902,19790316,20011031,2001.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
20,1013,50906,2902,19790316,20021031,2002.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
21,1013,50906,2902,19790316,20031031,2003.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
22,1013,50906,2902,19790316,20041031,2004.0,0.1429,0.1429,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
23,1013,50906,2902,19790316,20051031,2005.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
24,1013,50906,2902,19790316,20061031,2006.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
25,1013,50906,2902,19790316,20071031,2007.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
26,1013,50906,2902,19790316,20081031,2008.0,1.0000,1.0000,1.0000,10.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
27,1013,50906,2902,19790316,20090930,2009.0,1.0000,1.0000,1.0000,9.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
28,1013,50906,2902,19790316,20100930,2010.0,1.0000,1.0000,1.0000,9.0,...,45.0,45201020.0,334210.0,1,3661,180.0,940.0,0.0,20101210.0,19790316.0
29,1034,65832,20007,19840215,20001231,2000.0,1.0000,1.0000,1.0000,12.0,...,35.0,35202010.0,325412.0,1,2834,283.0,905.0,0.0,20081231.0,19980220.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108653,315318,14406,54703,20140123,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,15.0,15101050.0,325320.0,1,2870,360.0,925.0,0.0,20120109.0,19980220.0
108654,315318,14406,54703,20140123,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,15.0,15101050.0,325320.0,1,2870,360.0,925.0,0.0,20120109.0,19980220.0
108655,315629,16348,55719,20161101,20161231,2016.0,1.0000,1.0000,0.0309,12.0,...,45.0,45301020.0,334418.0,90,3679,360.0,925.0,0.0,20120109.0,19980220.0
108656,315629,16348,55719,20161101,20171231,2017.0,1.0000,1.0000,0.0337,12.0,...,45.0,45301020.0,334418.0,90,3679,360.0,925.0,0.0,20120109.0,19980220.0
108657,315639,15419,55305,20150619,20151231,2015.0,1.0000,1.0000,1.0859,12.0,...,35.0,35201010.0,325414.0,90,2836,360.0,925.0,0.0,20120109.0,19980220.0
108658,315639,15419,55305,20150619,20161231,2016.0,1.0000,1.0000,1.0552,12.0,...,35.0,35201010.0,325414.0,90,2836,360.0,925.0,0.0,20120109.0,19980220.0
108659,315639,15419,55305,20150619,20171231,2017.0,1.0000,1.0000,1.2022,12.0,...,35.0,35201010.0,325414.0,90,2836,360.0,925.0,0.0,20120109.0,19980220.0
108660,315887,14344,54677,20131212,20131231,2013.0,0.0833,0.0833,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20131212.0
108661,315887,14344,54677,20131212,20141231,2014.0,0.0833,0.0833,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20131212.0
108662,315887,14344,54677,20131212,20151231,2015.0,1.0000,1.0000,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20131212.0
108663,315887,14344,54677,20131212,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20131212.0
108664,315887,14344,54677,20131212,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,20.0,20303010.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20131212.0
108665,316056,14297,54641,20131202,20131231,2013.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,360.0,925.0,0.0,20120109.0,19980220.0
108666,316056,14297,54641,20131202,20141231,2014.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,360.0,925.0,0.0,20120109.0,19980220.0
108667,316056,14297,54641,20131202,20151231,2015.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,360.0,925.0,0.0,20120109.0,19980220.0
108668,316056,14297,54641,20131202,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,360.0,925.0,0.0,20120109.0,19980220.0
108669,316056,14297,54641,20131202,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,20.0,20102010.0,332510.0,1,3420,360.0,925.0,0.0,20120109.0,19980220.0
108670,317260,14756,54928,20140612,20141231,2014.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,19980220.0
108671,317260,14756,54928,20140612,20151231,2015.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,19980220.0
108672,317260,14756,54928,20140612,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,19980220.0
108673,317260,14756,54928,20140612,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,10.0,10101020.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,19980220.0
108674,317264,14642,54852,20140508,20150331,2014.0,1.0000,1.0000,1.0000,3.0,...,10.0,10102040.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20140508.0
108675,317264,14642,54852,20140508,20160331,2015.0,1.0000,1.0000,1.0000,3.0,...,10.0,10102040.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20140508.0
108676,317264,14642,54852,20140508,20170331,2016.0,1.0000,1.0000,1.0000,3.0,...,10.0,10102040.0,483111.0,1,4412,360.0,925.0,0.0,20120109.0,20140508.0
108677,317427,15920,55515,20160112,20161231,2016.0,1.0000,1.0000,1.0552,12.0,...,30.0,30202030.0,311411.0,1,2030,360.0,925.0,0.0,20120109.0,19980220.0
108678,318728,16496,55804,20161209,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,40.0,40301020.0,524113.0,1,6311,360.0,925.0,0.0,20120109.0,20161209.0
108679,318728,16496,55804,20161209,20171231,2017.0,1.0000,1.0000,1.0000,12.0,...,40.0,40301020.0,524113.0,1,6311,360.0,925.0,0.0,20120109.0,20161209.0
108680,318815,15904,55506,20151207,20151231,2015.0,1.0000,1.0000,1.4746,12.0,...,35.0,35201010.0,325414.0,90,2836,360.0,925.0,0.0,20120109.0,19980220.0
108681,318815,15904,55506,20151207,20161231,2016.0,1.0000,1.0000,1.2337,12.0,...,35.0,35201010.0,325414.0,90,2836,360.0,925.0,0.0,20120109.0,19980220.0
108682,319507,16469,55793,20161118,20161231,2016.0,1.0000,1.0000,1.0000,12.0,...,35.0,35202010.0,325414.0,90,2836,360.0,925.0,0.0,20120109.0,19980220.0

In [10]:
# Checking missing value for each variables (column)

wdrsdata.isnull().sum()

GVKEY        0
LPERMNO      0
LPERMCO      0
LINKDT       0
datadate     0
fyear        0
ajex         0
ajp          0
currtr       0
fyr          0
ismod        0
pddur        0
scf          0
src          0
upd          0
apdedate     0
fdate        0
pdate        0
acchg        0
acdo         0
aco          0
acodo        0
acominc      0
acox         0
act          0
aldo         0
am           0
ano          0
ao           0
aocidergl    0
            ..
prcc_c       0
prch_c       0
prcl_c       0
adjex_c      0
cshtr_f      0
dvpsp_f      0
dvpsx_f      0
mkvalt       0
prcc_f       0
prch_f       0
prcl_f       0
adjex_f      0
rank         0
au           0
auop         0
auopic       0
dlrsn        0
fyrc         0
ggroup       0
gind         0
gsector      0
gsubind      0
naics        0
priusa       0
sic          0
spcindcd     0
spcseccd     0
stko         0
dldte        0
ipodate      0
Length: 370, dtype: int64

In [19]:
# Defining Variables
# X is a predictor variable or an independent variable
# Y is a dependent variable or an outcome variable

X = wdrsdata[wdrsdata.columns[~wdrsdata.columns.isin(['ebit'])]]
y = wdrsdata[wdrsdata.columns[wdrsdata.columns.isin(['ebit'])]]
n_folds = 5                                            # 5-fold cross-validation
max_depth1 = 4                                       # maximum number of nodes for 1st decision tree
max_depth2 = 5                                       # maximum number of nodes for 2nd decision tree 
min_size = 10                                        # minimum number of training patterns
point = evaluate_algorithm(dataset, decision_tree, n_folds, max_depth, min_size)

NameError: name 'max_depth' is not defined

In [20]:
# Cross-validation:
# Split a dataset into k folds

def cross_validation_split(dfw, n_folds):
    wdrsdata_split = list()
    wdrsdata_copy = list(wdrsdata)
    fold_size = int(len(wdrsdata) / n_folds)
    for i in range(n_folds):
        fold = list()
        while len(fold) < fold_size:
            index = randrange(len(wdrsdata_copy))
            fold.append(wdrsdata_copy.pop(index))
        wdrsdata_split.append(fold)
    return wdrsdata_split

# Calculating accuracy percentage

def accuracy_metric(actual, predict):
    correct = 0
    for i in range(len(actual)):
        if actual[i] == predict[i]:
            correct += 1
    return correct / float(len(actual)) * 100.0

# Using a cross validation split for evaluating an algorithm

def evaluate_algorithm(wdrsdata, algorithm, n_folds, *args):
    folds = cross_validation_split(wdrsdata, n_folds)
    point = list()
    for fold in folds:
        train_set = list(folds)
        train_set.remove(fold)
        train_set = sum(train_set, [])
        test_set = list()
        for row in fold:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        predict = algorithm(train_set, test_set, *args)
        actual = [row[-1] for row in fold]
        accuracy = accuracy_metric(actual, predict)
        point.append(accuracy)
    return point

In [21]:
# Creating split:
# Spliting the dataset based on an attribute and an attribute value

def test_split(index, value, wdrsdata):
    left, right = list(), list()
    for row in dataset:
        if row[index] < value:
            left.append(row)
        else:
            right.append(row)
    return left, right

# Selecting the best split point for the dataset

def get_split(wdrsdata):
    class_values = list(set(row[-1] for row in wdrsdata))
    b_index, b_value, b_point, b_groups = 999, 999, 999, None
    for index in range(len(wdrsdata[0])-1):
        for row in wdrsdata:
            groups = test_split(index, row[index], wdrsdata)
            gini = gini_index(groups, class_values)
            if gini < b_point:
                b_index, b_value, b_point, b_groups = index, row[index], gini, groups
    return {'index':b_index, 'value':b_value, 'groups':b_groups}
 
# Creating a terminal node value

def to_terminal(group):
    outcomes = [row[-1] for row in group]
    return max(set(outcomes), key = outcomes.count)
 
# Creating child splits for a node or make terminal
# Checking both left and right Child

def split(node, max_depth, min_size, depth):
    left, right = node['groups']
    del(node['groups'])
    # check for a no split
    if not left or not right:
        node['left'] = node['right'] = to_terminal(left + right)
        return
    # Checking for max depth
    if depth >= max_depth:
        node['left'], node['right'] = to_terminal(left), to_terminal(right)
        return
    # Processing left child
    if len(left) <= min_size:
        node['left'] = to_terminal(left)
    else:
        node['left'] = get_split(left)
        split(node['left'], max_depth, min_size, depth + 1)
    # Processing right child
    if len(right) <= min_size:
        node['right'] = to_terminal(right)
    else:
        node['right'] = get_split(right)
        split(node['right'], max_depth, min_size, depth + 1)

In [22]:
# Creating Gini Index:
# Calculating the Gini index for the split dataset

def gini_index(groups, classes):
    # count all samples at split point
    n_instances = float(sum([len(group) for group in groups]))
    # sum weighted Gini index for each group
    gini = 0.0
    for group in groups:
        size = float(len(group))
        # avoid divide by zero
        if size == 0:
            continue
        score = 0.0
        # score the group based on the score for each class
        for class_val in classes:
            p = [row[-1] for row in group].count(class_val) / size
            score += p * p
        # weight the group score by its relative size
        gini += (1.0 - score) * (size / n_instances)
    return gini

In [23]:
# Decision tree:
# Building a decision tree

def build_tree(train, max_depth, min_size):
    root = get_split(train)
    split(root, max_depth, min_size, 1)
    return root
 
# Making a prediction with a decision tree

def predicted(node, row):
    if row[node['index']] < node['value']:
        if isinstance(node['left'], dict):
            return predicted(node['left'], row)
        else:
            return node['left']
    else:
        if isinstance(node['right'], dict):
            return predicted(node['right'], row)
        else:
            return node['right']

# Classification and Regression Tree Algorithm 

def decision_tree(train, test, max_depth, min_size):
    tree = build_tree(train, max_depth, min_size)
    predictions = list()
    for row in test:
        prediction = predicted(tree, row)
        predictions.append(prediction)
    return(predictions)